### PR TITLE
Enable passive location provider (needs translations)

### PR DESCRIPTION
**Pull request by supermamie**
This is a commit to implement issue #8 
There are translations needed, and some improvements to add so the GPS/NETWORK are not called if PASSIVE already send a correct location.

### CODE REVIEW

**Comment by bfabiszewski** [comment]
Thanks for the contribution!
Sorry for late answer. I've been away.

Do you think you could simplify the menu for choosing providers? 
Instead of listing all combinations of different providers I think it would be better to have checkboxes (with condition that at least one option is selected):
- [x] GPS
- [ ] network
- [ ] passive

Regarding further improvements that you mention I will have to test the passive provider in real life usage first, to see how it works.

**Comment by supermamie** [comment]
I've started to work on a way to have 2 different timers, one for passive, and one for GPS/Network, so that the GPS/Network are only called after X minutes/seconds if no passive info were received.
The bad thing is that I've modified the app a lot and I'm not sure at all to go in a good direction with that.

I'll do a branch to add checkboxes, that will be a nice thing to do (no idea of when I'll have time).

For the passive only (which I use), it works if there are already other services requesting location (like the google thing that log every places).
I want to get ride of those so the feature with 2 timers will help :)

**Comment by bfabiszewski** [comment]
I wanted to avoid timers to keep the location updates as lightweight as possible – mainly to preserve battery. I'll be still interested in the results of your tests.

**Comment by supermamie** [comment]
I think I did not enough testing.
What I want to do if to "cancel" the next GPS/Network request if a Passive location is received.

What I remember is that if a passive network location was received, when resetting the GPS/Network request, the GPS was directly activated.

**Pull request closed without merging**
