### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by dvdcr**

### CODE REVIEW

**Comment by bfabiszewski** [comment]
Thanks a lot for the contribution!

Could you please remove all `strings`/`string-arrays` with `translatable="false"` attribute? They should not be included in localized folders. 
As you can see they cause compile warnings and travis build fails.

Shouldn't `<item>Red and GPS</item>` be `<item>Red y GPS</item>`? ;)

**Comment by dvdcr** [comment]
Sorry, I'm a newbie on github and on Android develpment too ;) I'll fix it.

**Comment by dvdcr** [comment]
Is there any way of checking this errors from my PC before commiting the changes? I dont want to annoy you with little errors like than until it will be completely fixed.

**Comment by bfabiszewski** [comment]
Thanks, everything is fine now!

Regarding checking your changes locally, you could try to build the project on your PC and see if there are no warnings related to your additions.
You can also commit here and see the status of Travis builds for [pull requests](https://travis-ci.org/bfabiszewski/ulogger-android/pull_requests). You can click each build and see the [error message](https://travis-ci.org/bfabiszewski/ulogger-android/builds/388388062#L1972) of the failed compilation.
Also don't worry about committing multiple times.

Thanks again!

**Comment by dvdcr** [comment]
Thank you for sharing your code and let others learn of it!

**Comment by bfabiszewski** [comment]
@dvdcr 
Could you give me Spanish translation for "Nautical", referring to nautical units? And also Spanish abbreviation for nautical mile, if different than English "nm".
These two strings were added in the [new PR](https://github.com/bfabiszewski/ulogger-android/pull/39).

**Comment by dvdcr** [comment]
I can't access now to git. If you can wait a few days, I'll commit it later. If you want to include it now, "Nautical Units" is translated to Spanish as "Unidades Náuticas", "Nautical Mile" as "Milla Náutica", and the abbreviation is the same that in English.

**Comment by bfabiszewski** [comment]
Thanks for quick reply! You don't have to bother with git. I'll do it myself.
I'll just use "Náuticas" for "Nautical". The abbreviation will be "nm".

**Pull request merged**
