### PR TITLE
Update AndroidManifest.xml for api 29

### PR DESCRIPTION
**Pull request by Jhyrachy**
added support for API 29

Source: https://developer.android.com/training/location/permissions#background

### CODE REVIEW

**Comment by bfabiszewski** [comment]
Do you experience any problems with location updates?
I don't think this change is needed. The application uses foreground service to track location.
See: https://developer.android.com/training/location/permissions#foreground

**Comment by Jhyrachy** [comment]
Yes, I had some problems with tracking.  
But maybe it's the update's fault.  
I'll make some tests in the next few days with another device and will report.

Thanks for the quick answer

**Comment by bfabiszewski** [comment]
Be sure to disable any battery optimization settings for the app

**Comment by bfabiszewski** [comment]
I am closing it now. Please reopen if you have any new info.

**Pull request closed without merging**
